### PR TITLE
Add IntelliJ files to .gitignore

### PR DESCRIPTION
**Pull request by edf42001**
Is this something that should be done?

### CODE REVIEW

**Comment by davidbernat** [comment]
No, InteliJ files are your local configuration. Also, large data files are
frowned upon.

PS Could you kindly transfer the repository to my ownership? Simply so I
can share proprietary information in there.

**Comment by edf42001** [comment]
Wait, so should the files in the .idea folder for my local configuration be ignored in this repository or should they be included?

**Comment by davidbernat** [comment]
Ignored. You should add .idea/ to .gitignore. And a few other files, .iml,
etc. it’s obviously not a sin but it’s a sign you know what you’re doing,
etc, etc.

**Comment by edf42001** [comment]
Do want to be the only one merging any branches, or should I?

**Comment by davidbernat** [comment]
You can. No need to be overly strict about it. I want to be reviewing the
code to provide instruction and mentor ship etc. others will feel more
serious in production environments.

**Pull request merged**
